# Generated by Django 4.1.3 on 2024-06-23 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='menu_item',
            new_name='menuitem_id',
        ),
    ]
